# Generated by Django 2.2.6 on 2019-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=512)),
            ],
        ),
    ]
